### ISSUE TITLE
Autostart from command-line

### ISSUE THREAD

**Issue by guanzhangrtk** [Akhlys/Roboter#1]
Hi, thanks for this great software, and hot keys now work on macOS.

I was wondering would it be possible to add an option to auto-start with a script file via the command line, like:

`java -jar roboter.v.1.1.jar -f octopath.rbt`

and it would load the script and start automatically.

BTW are there any libraries that can be used such that you can send the keystrokes/mouse clicks to another app in the background such that it doesn't always have to be in the foreground? Thanks!

**Comment by Akhlys** [comment]
now I know why you wanted me to make a github..
I guess adding it would be easy enough. But I don't think anyone but you would have that requirement so.. low priority for me ;P

As for the question.. I'm not 100% sure, but I guess if something that had no focus would want key input it would have to implement an API for it because by default it just won't get them. 
if it is for an idle game or something, you could add a click to the task bar to bring it up, a click to the window and a key input followed to a click beside the window to bring what you were doing to focus. but that's just a workaround for a possible use case. But in general, an autoclicker and a background app don't mix

**Comment by guanzhangrtk** [comment]
> now I know why you wanted me to make a github..
> I guess adding it would be easy enough. But I don't think anyone but you would have that requirement so.. low priority for me ;P

Well you never know, other people may find it useful too. I guess I can prolly add this myself, but first I'll need to read through and understand the entire code base :-)

> if it is for an idle game or something, you could add a click to the task bar to bring it up, a click to the window and a key input followed to a click beside the window to bring what you were doing to focus. but that's just a workaround for a possible use case. But in general, an autoclicker and a background app don't mix

[This](https://guanzhang.medium.com/setting-up-gesture-macros-on-ios-using-macos-for-mobile-games-4891b1920275) is what I'm trying to do such that I can autotap on my iOS device using a computer. However the issue is if I do that then I won't be able to use my computer since the other apps need to be in the foreground. My current workaround is to do all this in a VM so it runs in the background, but ideally the dev of KeyPad will be able to modify his code such that it can take keystrokes in the background from your app, then everything will just work :-)

**Comment by Akhlys** [comment]
>first I'll need to read through and understand the entire code base

I added less comments that I normally would because thjat was mainly just a quick thing for myself :D 
But really, if you just wanted to load something and start it, you'd just have to do that at the end of the main method:

```
try (FileInputStream fileIn = new FileInputStream(File theFileFromParameter);
	ObjectInputStream objIn = new ObjectInputStream(fileIn)) {
	roboterGui.setActionsPacket((ActionsPacket)objIn.readObject());
	roboterGui.btnStartStop.doClick();
} catch (IOException | ClassNotFoundException ex) {
	ex.printStackTrace();
	JOptionPane.showMessageDialog(this, "Could not load provided file " + fileFromParameter.toString(), "Load", JOptionPane.ERROR_MESSAGE);
}
```
(or rather, put that in an extra function and execute that one, because btnStartStop is not visible outside of the class and neither is the load function)

as said, it would be pretty easy. The issue is, that if I added it, I would have to split that up into multiple commands, one to autoload, one to autostart, because always doing both seems not that good. also, something like "start minimized" would have to be added so the clicks don't land on the app itself. and this may lead to plenty of more problems itself (if it can even be done. I guess so, but I never tried to do that before)  
All in all, plenty of work for something I will never use and neither will anyone but you ;) alone the fact that no other autoclicker can do this is a good gauge that nobody needs it ;P

soooo.. all in all.. I might add that sometime, but don't count on it, I'll probably don't. Maybe I'll just add autoloading of a saved state, no autostarting, because I an see how people that use it only on one thing might have a use for that.

>but ideally the dev of KeyPad will be able to modify his code such that it can take keystrokes in the background from your app

just so we're clear.. if he added an API for background keystrokes, any app that would want to use it would have to call his api. it won't just happen by itself by magic. So even if he added something like that, You'd have to fork the autoclicker and implement using his api instead of normal clicks to use it (which you'd have to do yourself because I won't do that ;)). 
Else he would have to make a global key grabber that redirects everything to his app, and if he did (he won't because that's crazy) every key you type, every click you make, would also affect whatever is running there.
I think you really have no choice between either a VM or having it in the foregound.

Honestly, I don't see why you take so much pains for mobile games. I mean sure, you use mac, so you don't know how great normal games are (mostly joking but you can't deny a kernel of truth ;P) but I have yet to see a mobile game worth anything (save those that would have no need for a clicker)
